name: JoinFull
version: '1.0.0-OmxRealm'
main: org.dw363.JoinFull
api-version: '1.21'
load: STARTUP
authors: [dw363]
description: Плагин, позволяющий с определёнными правами зайти на сервер сверх лимита, создано специально для сервера OmxRealm. Project The OMX
website: https://github.com/Hacker123ter
